"""updates to models.py

Revision ID: xyz123  # Change the revision identifier to a unique value
Revises: be4849a1f317  # Specify the revision that this one revises
Create Date: 2024-04-08 16:51:21.034422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'xyz123'  # Change the revision identifier to a unique value
down_revision = 'be4849a1f317'  # Update with the previous revision identifier
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_column', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_column')
    # ### end Alembic commands ###
